version: 0.0

os: linux
files:
  - source: /
    destination: /var/app/current
hooks:
  BeforeInstall:
    - location: scripts/shell/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/shell/restart_server.sh
      timeout: 300
      runas: ec2-user

